name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bench:
    name: Build
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - name: Install packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
